name: 'SwiftTest by SwiftActions'
author: 'SwiftActions'
description: 'Executes unit tests of a Swift project.'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  verbose:
    description: "Increase verbosity to include informational output"
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ github.action_path }}
        swift run SwiftTest \
          --verbose ${{ inputs.verbose }} \
          --working-directory ${{ github.workspace }}
      shell: bash
